### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by pawamoy** [blueswen/mkdocs-swagger-ui-tag#1]
Hi! Did you try with the slate theme of Material for MkDocs enabled?

I actually integrated the Swagger UI in some projects docs (with a few lines of Javascript), and it looks nice with a light theme, but is unreadable with a dark theme. Maybe you found a way to improve that.

**Comment by blueswen** [comment]
Yes, I have tried with the slate theme of Material for MkDocs, then I found it was unreadable. So I add a [body background color](https://github.com/blueswen/mkdocs-swagger-ui-tag/blob/main/mkdocs_swagger_ui_tag/swagger-ui/swagger.html#L10)(default: white) to prevent Swagger UI's transparent background as a workaround.

<img width="1388" alt="dark-mode-demo" src="https://user-images.githubusercontent.com/1564148/173259879-59e0a88b-8e31-4034-9313-94623715a8ab.png">

I also have tried some dark mode css for Swagger UI, but they does not look good for me. Maybe https://github.com/swagger-api/swagger-ui/pull/5964 could solve this. I will try this PR's css latter.

**Comment by pawamoy** [comment]
I see, thanks! Feel free to close :slightly_smiling_face:

**Comment by pawamoy** [comment]
Woohoo, great job! Looks nice :slightly_smiling_face: Closing :smile: !
