### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by yosuke-nakamura** [blueswen/mkdocs-swagger-ui-tag#14]
How to use?

I have an OpenAPI in yaml format. I want to use that file to generate files in MkDocs.
I cannot generate it in MkDocs even if I save the openapi.yaml file in the docs/assets/javascripts folder.

Am I using it incorrectly?

Thank you in advance.

![image](https://github.com/blueswen/mkdocs-swagger-ui-tag/assets/82066945/a20627c6-f231-40e5-aa6c-1553dab60419)

**Comment by blueswen** [comment]
Hi @yosuke-nakamura 

You can check the example on [static-file demo](https://blueswen.github.io/mkdocs-swagger-ui-tag/demo/static-file/) and the markdown files are in [here](https://github.com/blueswen/mkdocs-swagger-ui-tag/tree/main/demo-mkdocs/docs/demo).

Please provide a reproducible project or GitHub repository link if you have further questions.
