### ISSUE TITLE
Mkdocs site_url not used to load asset

### ISSUE THREAD

**Issue by DennyWeinberg** [blueswen/mkdocs-swagger-ui-tag#15]
I host my mkdocs on gitlab pages, inside a group, so the url is: `https://namespace.gitlab.io/project`.
When using swagger-ui-doc, I specify `/assets/openapi.json`, which works great when doing a serve. However, when opening the gitlab page, I'm getting 404 because he tries to load the json from `https://namespace.gitlab.io/assets/openapi.json`, so `project` is missing here.
In my `mkdocs.yml`, I tried to specify the `site_url` then: `https://namespace.gitlab.io/project`, which still doesn't help. Same result.

Any ideas?

**Comment by blueswen** [comment]
Hi @DennyWeinberg

All OpenAPI file paths are processed using relative paths, such as `../../assets/openapi.json`. If this does not resolve your issue, you may provide your modocs.yml, Markdown files, and file structure.

**Comment by DennyWeinberg** [comment]
Yes that worked indeed. Might be useful to add that to the doc.

Thanks!
