### ISSUE TITLE
Do the same for ReDoc

### ISSUE THREAD

**Issue by DennyWeinberg** [blueswen/mkdocs-swagger-ui-tag#16]
First, thank you very much for your awesome mkdocs plugin!

It would be awesome to do the same for ReDoc, which is a bit nicer, but works nearly the same.

**Comment by rishabh-sagar-20** [comment]
Yes, please provide support for ReDoc as well.

**Comment by GarlicHiker** [comment]
+ 1

**Comment by blueswen** [comment]
Hi @DennyWeinberg @rishabh-sagar-20 @GarlicHiker ,

I took some time to create a sibling project for [Redoc](https://github.com/Redocly/redoc). Check the new plugin `mkdocs-redoc-tag` on [GitHub](https://github.com/blueswen/mkdocs-redoc-tag) or [demo website](https://blueswen.github.io/mkdocs-redoc-tag/).

Hope this helps you!
