### ISSUE TITLE
Inbuilt search is not working for content generated by this plugin

### ISSUE THREAD

**Issue by GarlicHiker** [blueswen/mkdocs-swagger-ui-tag#18]
Hello,
above all, thank you for creating this plugin! It's awesome!

I stumbled across one issue: when I add the plugin in the suggested way to my project, and build the static website, the OpenAPI specification generated by this plugin seems to be invisible to the default search feature provided by Material for MkDocs.  Is the there a known way (a workaround) how to put the searching into operation, or is this a bug to be fixed?
Thank you!

**Comment by blueswen** [comment]
Hi @GarlicHiker ,

This isn't a bug; the content is unsearchable. Because the searching feature is based on the markdown file contents, Swagger UI or OpenAPI contents are generated by JavaScript when you open the web page.
