### ISSUE TITLE
Schema not being displayed properly when navigating to page via sidebar

### ISSUE THREAD

**Issue by stephenjlevy** [blueswen/mkdocs-swagger-ui-tag#2]
When loading a markdown page directly (when running via `mkdocs serve`), the schema shows up as expected, however, when navigating to that same page via the sidebar, only the first part of the schema is displayed. The chrome console shows the following error:

`Uncaught TypeError: parent.update_swagger_ui_iframe_height is not a function
    at ResizeObserver.<anonymous> (swagger-ff203020.html:49:14)`

Everything appears to work as expected when loading a built site, rather than using `mkdocs serve`.

**Comment by blueswen** [comment]
@stephenjlevy Sorry for the late replying. I can not reproduce the bug you described. Could you give me a sample mkdocs project or a screen recording?

**Comment by blueswen** [comment]
@stephenjlevy Are you using the mkdocs-material theme and enable the [Instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#instant-loading) feature? I reproduced the same bug as you described with enabling Instant loading.

**Comment by blueswen** [comment]
@stephenjlevy Version 0.3.2 is compatible with mkdocs-material's [Instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#instant-loading) feature now. Maybe new version could solve your problem.
