### ISSUE TITLE
Confusing position of the OAuth popup dialog

### ISSUE THREAD

**Issue by robvanderleek** [blueswen/mkdocs-swagger-ui-tag#5]
In the plain generated Swagger documentation the authorization dialog is positioned at the top of the page:

<img width="562" alt="swagger-docs" src="https://user-images.githubusercontent.com/5324924/185838211-cc48d641-8a9f-4849-a92e-368768192e77.png">

However, in the mkdocs embedded Swagger documentation the authorization dialog is centered in the iframe:

<img width="562" alt="swagger-mkdocs" src="https://user-images.githubusercontent.com/5324924/185838329-0882cf1e-b186-4fcb-b281-b6c69f0830ca.png">

This behaviour can be confusing to users as they need to scroll down after clicking the Authorize button to find the popup.

Not sure if this behaviour can be changed/configured, let me know if I need to supply more details.

**Comment by blueswen** [comment]
Hi @robvanderleek,

I added some script to control the authorize modal position when the page is scrolling. The authorize modal will try to stay at the vertical center of the whole window, but it will stick to the top or bottom of the iframe when the iframe is not in the window.

You can check this feature in v0.4.3 or the live demo in https://blueswen.github.io/mkdocs-swagger-ui-tag/demo/multiple/, which also shows it works with multiple Swagger UI opening authorize modal at the same time.

**Comment by robvanderleek** [comment]
Hi @blueswen 

That's just perfect 🤩 

That solves the last issue I had embedding the Swagger docs in mkdocs, thanks for all the support.
