### ISSUE TITLE
Issue with Special Charaters in Paths

### ISSUE THREAD

**Issue by mfeisel** [blueswen/mkdocs-swagger-ui-tag#6]
Hi,
we have for example a @ in the Pathname of document Directories.
This leads this plugin is putting the file swagger-<...>.html in ...%40... Directory. Which then is not found in the resulting webpages.

For me it looks if you change line 98 in plugin.py from

```python
page_dir = os.path.dirname(os.path.join(config['site_dir'], page.url))
```

to 

```python
page_dir = os.path.dirname(os.path.join(config['site_dir'], urlunquote(page.url)))
```

will fix the issue, but I do not know if there is any other side effect.

Would be great if you can have a look in this.
Many thanks.
Kind regards

**Comment by blueswen** [comment]
@mfeisel Thanks for digging into the details.

It seems to work perfectly with ```urlunquote(urllib.parse.unquote)``` to deal with the special characters in the path. I fixed this in v0.4.3. Could you check that it is okay in your project?
